defaultIgnores: false
rules:
  body-case: [0]
  body-empty: [0]
  body-full-stop: [0]
  body-leading-blank: [2, always]
  body-max-length: [0]
  body-max-line-length: [2, always, 72]
  body-min-length: [0]
  footer-empty: [0]
  footer-leading-blank: [2, always]
  footer-max-length: [0]
  footer-max-line-length: [2, always, 72]
  footer-min-length: [0]
  header-case: [2, always, lower-case]
  header-full-stop: [2, never, "."]
  header-max-length: [2, always, 50]
  header-min-length: [0]
  header-trim: [2, always]
  references-empty: [0]
  scope-case: [2, always, lower-case]
  scope-empty: [2, always]
  scope-enum: [2, always, []]
  scope-max-length: [0]
  scope-min-length: [0]
  signed-off-by: [0]
  subject-case: [2, always, lower-case]
  subject-empty: [2, never]
  subject-exclamation-mark: [0]
  subject-full-stop: [2, never, "."]
  subject-max-length: [0]
  subject-min-length: [0]
  trailer-exists: [0]
  type-case: [2, always, lower-case]
  type-empty: [2, never]
  type-enum: [2, always, [build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test]]
  type-max-length: [0]
  type-min-length: [0]
