name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Install commitlint
        run: npm install --global @commitlint/cli
      - name: Verify current commit
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose
      - name: Verify pull request commits
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
